const router=require('express').Router();const mongoose=require('mongoose');const multer=require('multer');
const User=require('../models/User');const Post=require('../models/Post');const Story=require('../models/Story');const Comment=require('../models/Comment');const Message=require('../models/Message');const Conversation=require('../models/Conversation');const Notification=require('../models/Notification');const AdminLog=require('../models/AdminLog');const Report=require('../models/Report');const FeedEvent=require('../models/FeedEvent');const Follow=require('../models/Follow');const AdCampaign=require('../models/AdCampaign');const AdEvent=require('../models/AdEvent');const AdConfig=require('../models/AdConfig');
const {emitToUsers}=require('../services/realtime');const {requireAuth,requireAdmin}=require('../middleware/auth');const {uploadFile,deleteMany}=require('../services/r2');const {getAdConfig}=require('../services/ads');
const adUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(_,f,cb)=>cb(null,/^image\/(jpeg|png|webp|avif)$/.test(f.mimetype))});
function safeRegex(v=''){return String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
async function logAction(req,action,targetType='',targetId='',details=''){await AdminLog.create({admin:req.currentUser._id,action,targetType,targetId:String(targetId||''),details:String(details||'').slice(0,240)}).catch(()=>{})}
router.get('/',requireAuth,requireAdmin,async(req,res)=>{const now=new Date(),day=new Date(now);day.setHours(0,0,0,0);const week=new Date(now.getTime()-7*864e5);const q=String(req.query.q||'').trim(),status=String(req.query.status||'all');const userFilter={};if(q){const rx=new RegExp(safeRegex(q),'i');userFilter.$or=[{name:rx},{username:rx},{phone:rx}]}if(status==='suspended')userFilter.isSuspended=true;if(status==='active')userFilter.isSuspended=false;if(status==='verified')userFilter.isVerified=true;if(status==='creator')userFilter.role='creator';
 const [users,suspended,verified,creators,newToday,newWeek,posts,hidden,postsToday,stories,messages,conversations,notifications,reportsOpen,viewsAgg,flagged,latestUsers,userResults,topPosts,topCreators,logs,eventAgg]=await Promise.all([
 User.countDocuments(),User.countDocuments({isSuspended:true}),User.countDocuments({isVerified:true}),User.countDocuments({role:'creator'}),User.countDocuments({createdAt:{$gte:day}}),User.countDocuments({createdAt:{$gte:week}}),Post.countDocuments(),Post.countDocuments({isHidden:true}),Post.countDocuments({createdAt:{$gte:day}}),Story.countDocuments({expiresAt:{$gt:now}}),Message.countDocuments(),Conversation.countDocuments(),Notification.countDocuments(),Report.countDocuments({status:{$in:['open','reviewing']}}),Post.aggregate([{$group:{_id:null,views:{$sum:{$ifNull:['$viewCount',0]}},likes:{$sum:{$ifNull:['$likeCount',0]}},comments:{$sum:{$ifNull:['$commentCount',0]}},saves:{$sum:{$ifNull:['$saveCount',0]}},shares:{$sum:{$ifNull:['$shareCount',0]}}}}]),Report.find({status:{$in:['open','reviewing']}}).sort({createdAt:-1}).limit(40).populate('reporter','name username avatarUrl').populate('reportedUser','name username avatarUrl').lean(),User.find().sort({createdAt:-1}).limit(12).lean(),User.find(userFilter).sort({createdAt:-1}).limit(60).lean(),Post.find({isHidden:false}).sort({qualityScore:-1,viewCount:-1}).limit(10).populate('author','name username avatarUrl').lean(),User.find({isSuspended:false}).sort({followerCount:-1,createdAt:-1}).limit(10).lean(),AdminLog.find().sort({createdAt:-1}).limit(30).populate('admin','name username').lean(),FeedEvent.aggregate([{$match:{createdAt:{$gte:week}}},{$group:{_id:'$type',count:{$sum:1},value:{$sum:'$value'}}},{$sort:{count:-1}}])]);
 const e=viewsAgg[0]||{views:0,likes:0,comments:0,saves:0,shares:0};const stats={users,suspendedUsers:suspended,verifiedUsers:verified,creators,newToday,newWeek,posts,hiddenPosts:hidden,postsToday,activeStories:stories,messages,conversations,notifications,reportsOpen,...e};const system={mongo:mongoose.connection.readyState===1,r2:!!(process.env.R2_ACCOUNT_ID&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY&&process.env.R2_BUCKET&&process.env.R2_PUBLIC_URL),redis:!!process.env.REDIS_URL,push:!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY),otp:process.env.OTP_REQUIRED==='true',siteUrl:process.env.SITE_URL||'SITE_URL o‘rnatilmagan',nodeEnv:process.env.NODE_ENV||'development'};res.set('Cache-Control','no-store');res.render('admin/index',{title:'Admin',stats,flagged,latestUsers,userResults,topPosts,topCreators,logs,eventAgg,system,q,status})});
router.post('/users/:id/suspend',requireAuth,requireAdmin,async(req,res)=>{const u=await User.findById(req.params.id);if(u&&u.role!=='admin'){u.isSuspended=!u.isSuspended;u.suspendedUntil=null;await u.save();await logAction(req,u.isSuspended?'user.suspend':'user.activate','user',u._id,`@${u.username}`)}res.redirect(req.get('referer')||'/admin')});
router.post('/users/:id/verify',requireAuth,requireAdmin,async(req,res)=>{const u=await User.findById(req.params.id);if(u){u.isVerified=!u.isVerified;await u.save();await logAction(req,u.isVerified?'user.verify':'user.unverify','user',u._id,`@${u.username}`)}res.redirect(req.get('referer')||'/admin')});
router.post('/users/:id/role',requireAuth,requireAdmin,async(req,res)=>{const u=await User.findById(req.params.id);const role=['user','creator','moderator'].includes(req.body.role)?req.body.role:'user';if(u&&u.role!=='admin'){u.role=role;await u.save();await logAction(req,'user.role','user',u._id,`@${u.username} → ${role}`)}res.redirect(req.get('referer')||'/admin')});
router.post('/posts/:id/toggle',requireAuth,requireAdmin,async(req,res)=>{const p=await Post.findById(req.params.id).populate('author','username');if(p){p.isHidden=!p.isHidden;if(p.isHidden)p.reports=0;await p.save();await logAction(req,p.isHidden?'post.hide':'post.show','post',p._id,p.author?`@${p.author.username}`:'')}res.redirect(req.get('referer')||'/admin')});
router.post('/reports/:id/action',requireAuth,requireAdmin,async(req,res)=>{const r=await Report.findById(req.params.id);if(!r)return res.sendStatus(404);const action=['dismiss','hide_content','warn','suspend_24h','suspend_7d','ban'].includes(req.body.action)?req.body.action:'dismiss';if(action==='hide_content'){if(r.targetType==='post')await Post.findByIdAndUpdate(r.targetId,{isHidden:true});else if(r.targetType==='story')await Story.findByIdAndUpdate(r.targetId,{isHidden:true});else if(r.targetType==='comment')await Comment.findByIdAndUpdate(r.targetId,{isHidden:true});else if(r.targetType==='message')await Message.findByIdAndUpdate(r.targetId,{text:'',deletedForEveryoneAt:new Date()})}if(['suspend_24h','suspend_7d','ban'].includes(action)&&r.reportedUser){const u=await User.findById(r.reportedUser);if(u&&u.role!=='admin'){u.isSuspended=true;u.suspendedUntil=action==='suspend_24h'?new Date(Date.now()+864e5):action==='suspend_7d'?new Date(Date.now()+7*864e5):null;await u.save()}}if(action==='warn'&&r.reportedUser)await Notification.create({user:r.reportedUser,actor:req.currentUser._id,type:'moderation',text:'Kontentingiz bo‘yicha moderator ogohlantirishi mavjud. Qoidalarga rioya qiling.'}).catch(()=>{});r.status=action==='dismiss'?'dismissed':'actioned';r.action=action;r.reviewedBy=req.currentUser._id;r.reviewedAt=new Date();await r.save();await logAction(req,'report.'+action,r.targetType,r.targetId,`report:${r._id}`);res.redirect('/admin#moderation')});
router.post('/announce',requireAuth,requireAdmin,async(req,res)=>{const text=String(req.body.text||'').trim().slice(0,180),target=['all','creators'].includes(req.body.target)?req.body.target:'all';if(text){const filter={isSuspended:false,_id:{$ne:req.currentUser._id}};if(target==='creators')filter.role='creator';const ids=await User.find(filter).select('_id').lean();for(let i=0;i<ids.length;i+=500)await Notification.insertMany(ids.slice(i,i+500).map(u=>({user:u._id,actor:req.currentUser._id,type:'system',text})),{ordered:false}).catch(()=>{});emitToUsers(ids.map(u=>String(u._id)),'notification',{text,type:'system'});await logAction(req,'system.announce','notification',target,`${ids.length} user · ${text}`)}res.redirect('/admin#announcement')});

function adFormValue(req, existing={}) {
  const placementInput=Array.isArray(req.body.placements)?req.body.placements:[req.body.placements].filter(Boolean);
  const placements=placementInput.filter(x=>AdCampaign.PLACEMENTS.includes(x));
  let clickUrl;
  try{clickUrl=new URL(String(req.body.clickUrl||existing.clickUrl||''));if(!['http:','https:'].includes(clickUrl.protocol))throw new Error()}catch(_){throw new Error("Reklama havolasi http:// yoki https:// bilan boshlansin.")}
  const toDate=value=>value?new Date(value):null;
  const startsAt=toDate(req.body.startsAt)||existing.startsAt||new Date();
  const endsAt=toDate(req.body.endsAt);
  if(endsAt&&endsAt<=startsAt)throw new Error('Tugash vaqti boshlanish vaqtidan keyin bo‘lsin.');
  if(!placements.length)throw new Error('Kamida bitta reklama joylashuvini tanlang.');
  return {name:String(req.body.name||'').trim().slice(0,80),advertiserName:String(req.body.advertiserName||'').trim().slice(0,80),title:String(req.body.title||'').trim().slice(0,100),body:String(req.body.body||'').trim().slice(0,260),clickUrl:clickUrl.toString(),ctaText:String(req.body.ctaText||"Saytga o'tish").trim().slice(0,32),placements,audience:['all','guests','members'].includes(req.body.audience)?req.body.audience:'all',status:['draft','active','paused','ended'].includes(req.body.status)?req.body.status:'draft',startsAt,endsAt,priority:Math.min(10,Math.max(1,Number(req.body.priority)||5)),priceModel:['cpm','cpc','flat'].includes(req.body.priceModel)?req.body.priceModel:'cpm',unitPrice:Math.max(0,Number(req.body.unitPrice)||0),budget:Math.max(0,Number(req.body.budget)||0),updatedBy:req.currentUser._id};
}
async function renderAdForm(req,res,{campaign=null,error=null,status=200}={}){res.status(status).render('admin/ad-form',{title:campaign?'Reklamani tahrirlash':'Yangi reklama',campaign,error})}

router.get('/ads',requireAuth,requireAdmin,async(req,res)=>{const since=new Date(Date.now()-7*864e5);const [campaigns,config,summary,daily]=await Promise.all([AdCampaign.find().sort({status:1,priority:-1,updatedAt:-1}).lean(),getAdConfig(),AdCampaign.aggregate([{$group:{_id:null,impressions:{$sum:'$impressions'},clicks:{$sum:'$clicks'},revenue:{$sum:'$revenue'},budget:{$sum:'$budget'}}}]),AdEvent.aggregate([{$match:{createdAt:{$gte:since}}},{$group:{_id:{day:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},type:'$type'},count:{$sum:1},revenue:{$sum:'$revenue'}}},{$sort:{'_id.day':1}}])]);const totals=summary[0]||{impressions:0,clicks:0,revenue:0,budget:0};totals.ctr=totals.impressions?totals.clicks/totals.impressions*100:0;res.set('Cache-Control','no-store');res.render('admin/ads',{title:'Reklama markazi',campaigns,config,totals,daily})});
router.get('/ads/new',requireAuth,requireAdmin,(req,res)=>renderAdForm(req,res));
router.post('/ads',requireAuth,requireAdmin,adUpload.single('image'),async(req,res)=>{let uploaded=null;try{const data=adFormValue(req);if(!req.file)throw new Error('Reklama rasmi tanlanishi kerak.');uploaded=await uploadFile(req.file,'ads',{maxEdge:1600,quality:86});const campaign=await AdCampaign.create({...data,imageUrl:uploaded.url,imageKey:uploaded.key,thumbUrl:uploaded.thumbUrl||uploaded.url,thumbKey:uploaded.thumbKey||'',createdBy:req.currentUser._id});await logAction(req,'ad.create','ad',campaign._id,campaign.name);res.redirect('/admin/ads')}catch(error){if(uploaded)deleteMany([uploaded.key,uploaded.thumbKey]).catch(()=>{});renderAdForm(req,res,{campaign:{...req.body,placements:Array.isArray(req.body.placements)?req.body.placements:[req.body.placements].filter(Boolean)},error:error.message||'Reklama saqlanmadi.',status:400})}});
router.get('/ads/:id/edit',requireAuth,requireAdmin,async(req,res)=>{const campaign=await AdCampaign.findById(req.params.id).lean();if(!campaign)return res.sendStatus(404);renderAdForm(req,res,{campaign})});
router.post('/ads/:id',requireAuth,requireAdmin,adUpload.single('image'),async(req,res)=>{let uploaded=null;try{const campaign=await AdCampaign.findById(req.params.id);if(!campaign)return res.sendStatus(404);const data=adFormValue(req,campaign);if(req.file){uploaded=await uploadFile(req.file,'ads',{maxEdge:1600,quality:86});data.imageUrl=uploaded.url;data.imageKey=uploaded.key;data.thumbUrl=uploaded.thumbUrl||uploaded.url;data.thumbKey=uploaded.thumbKey||''}const oldKeys=req.file?[campaign.imageKey,campaign.thumbKey]:[];Object.assign(campaign,data);await campaign.save();if(oldKeys.length)deleteMany(oldKeys).catch(()=>{});await logAction(req,'ad.update','ad',campaign._id,campaign.name);res.redirect('/admin/ads')}catch(error){if(uploaded)deleteMany([uploaded.key,uploaded.thumbKey]).catch(()=>{});renderAdForm(req,res,{campaign:{_id:req.params.id,...req.body,placements:Array.isArray(req.body.placements)?req.body.placements:[req.body.placements].filter(Boolean)},error:error.message||'Reklama yangilanmadi.',status:400})}});
router.post('/ads/:id/status',requireAuth,requireAdmin,async(req,res)=>{const status=['draft','active','paused','ended'].includes(req.body.status)?req.body.status:'paused';const campaign=await AdCampaign.findByIdAndUpdate(req.params.id,{status,updatedBy:req.currentUser._id},{new:true});if(campaign)await logAction(req,'ad.status','ad',campaign._id,`${campaign.name} → ${status}`);res.redirect('/admin/ads')});
router.post('/ads/settings',requireAuth,requireAdmin,async(req,res)=>{await AdConfig.findOneAndUpdate({key:'global'},{$set:{enabled:req.body.enabled==='on',feedInterval:Math.min(20,Math.max(3,Number(req.body.feedInterval)||5)),ctaDelaySeconds:Math.min(10,Math.max(1,Number(req.body.ctaDelaySeconds)||3)),maxAdsPerPage:Math.min(20,Math.max(1,Number(req.body.maxAdsPerPage)||8)),profileEnabled:req.body.profileEnabled==='on',chatsEnabled:req.body.chatsEnabled==='on',label:String(req.body.label||'Reklama').trim().slice(0,24),updatedBy:req.currentUser._id}},{upsert:true});await logAction(req,'ad.settings','ad_config','global','Reklama sozlamalari yangilandi');res.redirect('/admin/ads')});
module.exports=router;
