const router=require('express').Router();const bcrypt=require('bcryptjs');const crypto=require('crypto');const rateLimit=require('express-rate-limit');
const User=require('../models/User');const LoginSession=require('../models/LoginSession');const {normalizePhone,isValidPhone}=require('../utils/phone');const {sendOtp,verifyOtp}=require('../services/otp');const {sessionHash}=require('../middleware/security');
const authLimiter=rateLimit({windowMs:10*60*1000,max:20,standardHeaders:'draft-8',legacyHeaders:false});
function nextSafe(v){return v&&String(v).startsWith('/')?String(v):'/feed'}
async function recordSession(req,user){await LoginSession.create({user:user._id,sessionIdHash:sessionHash(req),ipHash:crypto.createHash('sha256').update(String(req.ip||'')+(process.env.SESSION_SECRET||'')).digest('hex').slice(0,24),userAgent:String(req.get('user-agent')||'').slice(0,300),lastSeenAt:new Date()}).catch(()=>{})}
async function createUserFromPending(req,res,verified=false){const p=req.session.pendingRegistration;if(!p)return res.redirect('/register');const user=await User.create({...p,phoneVerifiedAt:verified?new Date():null});delete req.session.pendingRegistration;req.session.userId=String(user._id);req.session.sessionVersion=Number(user.sessionVersion||0);await recordSession(req,user);res.redirect(nextSafe(req.body.next||req.session.afterAuth||'/feed'))}
router.get('/register',(req,res)=>res.render('auth/register',{title:'Ro‘yxatdan o‘tish',error:null,next:nextSafe(req.query.next),otpRequired:process.env.OTP_REQUIRED==='true'}));
router.post('/register',authLimiter,async(req,res)=>{try{const{name,username,password,ageConfirmed18}=req.body;const phone=normalizePhone(req.body.phone);const next=nextSafe(req.body.next);if(!ageConfirmed18)throw new Error('Platforma faqat 18+ foydalanuvchilar uchun.');if(!isValidPhone(phone))throw new Error('Telefon raqamni to‘liq kiriting. Masalan: +998 90 123 45 67.');if(!password||password.length<8)throw new Error('Parol kamida 8 belgi bo‘lsin.');const cleanUsername=String(username||'').toLowerCase().trim();if(!/^[a-z0-9._]{3,24}$/.test(cleanUsername))throw new Error('Username faqat a-z, 0-9, nuqta va _ bilan.');if(await User.exists({$or:[{phone},{username:cleanUsername}]}))throw new Error('Telefon raqam yoki username band.');const pending={name:String(name||'').trim().slice(0,60),username:cleanUsername,phone,email:phone.replace(/\D/g,'')+'@phone.lumi.local',passwordHash:await bcrypt.hash(password,12),ageConfirmed18:true,role:'user'};if(process.env.OTP_REQUIRED==='true'){req.session.pendingRegistration=pending;req.session.afterAuth=next;await sendOtp(phone,'register');return res.render('auth/verify',{title:'Telefonni tasdiqlash',error:null,phone,purpose:'register',next})}req.session.pendingRegistration=pending;return createUserFromPending(req,res,false)}catch(e){res.status(400).render('auth/register',{title:'Ro‘yxatdan o‘tish',error:e.message||'Ma’lumotlarni tekshiring.',next:nextSafe(req.body.next),otpRequired:process.env.OTP_REQUIRED==='true'})}});
router.post('/register/verify',authLimiter,async(req,res)=>{const p=req.session.pendingRegistration;if(!p)return res.redirect('/register');const ok=await verifyOtp(p.phone,'register',req.body.code);if(!ok)return res.status(400).render('auth/verify',{title:'Telefonni tasdiqlash',error:'Kod xato yoki muddati tugagan.',phone:p.phone,purpose:'register',next:nextSafe(req.body.next)});return createUserFromPending(req,res,true)});
router.post('/register/resend',authLimiter,async(req,res)=>{const p=req.session.pendingRegistration;if(!p)return res.redirect('/register');try{await sendOtp(p.phone,'register');res.render('auth/verify',{title:'Telefonni tasdiqlash',error:null,phone:p.phone,purpose:'register',next:nextSafe(req.body.next),resent:true})}catch(e){res.status(400).render('auth/verify',{title:'Telefonni tasdiqlash',error:e.message,phone:p.phone,purpose:'register',next:nextSafe(req.body.next)})}});
router.get('/login',(req,res)=>res.render('auth/login',{title:'Kirish',error:null,next:nextSafe(req.query.next)}));
router.post('/login',authLimiter,async(req,res)=>{const raw=String(req.body.phone||'').trim();const phone=normalizePhone(raw);const query=raw.includes('@')?{email:raw.toLowerCase()}:{phone};const user=await User.findOne(query);if(!user||user.isSuspended||!(await bcrypt.compare(req.body.password||'',user.passwordHash)))return res.status(401).render('auth/login',{title:'Kirish',error:'Telefon raqam yoki parol xato.',next:nextSafe(req.body.next)});req.session.userId=String(user._id);req.session.sessionVersion=Number(user.sessionVersion||0);await User.findByIdAndUpdate(user._id,{lastSeenAt:new Date()});await recordSession(req,user);res.redirect(nextSafe(req.body.next))});
router.get('/forgot-password',(req,res)=>res.render('auth/forgot',{title:'Parolni tiklash',error:null,step:'phone',phone:''}));
router.post('/forgot-password',authLimiter,async(req,res)=>{const phone=normalizePhone(req.body.phone);const user=await User.findOne({phone});if(!user)return res.status(400).render('auth/forgot',{title:'Parolni tiklash',error:'Bu raqamda akkaunt topilmadi.',step:'phone',phone});try{await sendOtp(phone,'reset');req.session.resetPhone=phone;res.render('auth/forgot',{title:'Parolni tiklash',error:null,step:'code',phone})}catch(e){res.status(400).render('auth/forgot',{title:'Parolni tiklash',error:e.message,step:'phone',phone})}});
router.post('/forgot-password/reset',authLimiter,async(req,res)=>{const phone=req.session.resetPhone;if(!phone)return res.redirect('/forgot-password');const password=String(req.body.password||'');if(password.length<8)return res.status(400).render('auth/forgot',{title:'Parolni tiklash',error:'Yangi parol kamida 8 belgi.',step:'code',phone});if(!(await verifyOtp(phone,'reset',req.body.code)))return res.status(400).render('auth/forgot',{title:'Parolni tiklash',error:'Kod xato yoki muddati tugagan.',step:'code',phone});await User.updateOne({phone},{$set:{passwordHash:await bcrypt.hash(password,12)},$inc:{sessionVersion:1}});delete req.session.resetPhone;res.redirect('/login')});
router.post('/logout',async(req,res)=>{if(req.currentUser)await LoginSession.updateMany({user:req.currentUser._id,sessionIdHash:sessionHash(req),revokedAt:null},{$set:{revokedAt:new Date()}}).catch(()=>{});req.session.destroy(()=>res.redirect('/'))});
module.exports=router;
