const router=require('express').Router();
const multer=require('multer');
const Post=require('../models/Post');const User=require('../models/User');const Follow=require('../models/Follow');const UserRelation=require('../models/UserRelation');const PostLike=require('../models/PostLike');const SavedPost=require('../models/SavedPost');const Comment=require('../models/Comment');const CommentLike=require('../models/CommentLike');const Report=require('../models/Report');
const {requireAuth}=require('../middleware/auth');const {uploadFile,deleteMany}=require('../services/r2');const {resolveMentions}=require('../utils/mentions');const {createNotification}=require('../services/notify');const {recordEvent,recalcQuality}=require('../services/feed');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:10},fileFilter:(_,f,cb)=>cb(null,/^(image\/(jpeg|png|webp|avif)|video\/(mp4|webm))$/i.test(f.mimetype))});
function wantsJson(req){return req.xhr||(req.get('accept')||'').includes('application/json')}
function countLegacy(post){return {likes:Math.max(Number(post.likeCount||0),post.likes?.length||0),comments:Math.max(Number(post.commentCount||0),post.comments?.length||0)}}
async function canAccessPost(user,post){
  if(!post)return false;const authorId=post.author?._id||post.author;if(!authorId)return false;
  let isPrivate=typeof post.author==='object'&&post.author!==null&&Object.prototype.hasOwnProperty.call(post.author,'isPrivate')?!!post.author.isPrivate:null;
  if(isPrivate===null){const a=await User.findById(authorId).select('isPrivate').lean();if(!a)return false;isPrivate=!!a.isPrivate}
  if(!isPrivate)return true;if(user&&String(user._id)===String(authorId))return true;if(!user)return false;
  return !!(await Follow.exists({follower:user._id,following:authorId,status:'accepted'}));
}

router.get('/create',requireAuth,(req,res)=>res.render('posts/create',{title:'Yangi post',error:null}));
router.post('/create',requireAuth,upload.array('images',10),async(req,res)=>{try{
  const files=req.files||[];if(!files.length)throw new Error('Kamida bitta rasm yoki video tanlang.');
  const uploaded=[];for(const f of files)uploaded.push(await uploadFile(f,'posts',{maxEdge:1800,quality:84}));
  const caption=String(req.body.caption||'').trim().slice(0,2200);const tags=String(req.body.tags||'').split(/[ ,#]+/).map(x=>x.trim().toLowerCase()).filter(Boolean).slice(0,20);const mentionedUsers=await resolveMentions(caption);
  const media=uploaded.map(x=>({url:x.url,key:x.key,type:x.type==='video'?'video':'image',width:x.width||0,height:x.height||0,thumbUrl:x.thumbUrl||'',thumbKey:x.thumbKey||''}));
  const post=await Post.create({author:req.currentUser._id,caption,imageUrl:media[0].url,imageKey:media[0].key,media,tags,mentions:mentionedUsers.map(u=>u._id),likeCount:0,commentCount:0});
  await User.findByIdAndUpdate(req.currentUser._id,{$inc:{postCount:1}}).catch(()=>{});
  await Promise.all(mentionedUsers.filter(u=>String(u._id)!==String(req.currentUser._id)).map(u=>createNotification({user:u._id,actor:req.currentUser._id,type:'mention',post:post._id,text:`@${req.currentUser.username} sizni postda belgiladi.`})));
  res.redirect('/p/'+post._id);
}catch(e){res.status(400).render('posts/create',{title:'Yangi post',error:e.message||'Post yuklanmadi.'})}});

router.post('/:id/like',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);const uid=String(req.currentUser._id);let legacyLiked=(post.likes||[]).some(id=>String(id)===uid);let row=await PostLike.findOne({post:post._id,user:req.currentUser._id});const liked=!!row||legacyLiked;let count=countLegacy(post).likes;
  if(liked){if(row)await row.deleteOne();if(legacyLiked)post.likes.pull(req.currentUser._id);count=Math.max(0,count-1);post.likeCount=count;await post.save();await recordEvent({user:req.currentUser._id,post:post._id,type:'unlike'})}
  else{await PostLike.create({post:post._id,user:req.currentUser._id});post.likeCount=count+1;await post.save();await recordEvent({user:req.currentUser._id,post:post._id,type:'like'});if(String(post.author)!==uid)await createNotification({user:post.author,actor:req.currentUser._id,type:'like',post:post._id,text:'Postingizga yoqdi bosildi.'}).catch(()=>{})}
  recalcQuality(post._id).catch(()=>{});if(wantsJson(req))return res.json({ok:true,liked:!liked,count:post.likeCount});res.redirect(req.get('referer')||'/feed')});

router.get('/:id/likes',async(req,res)=>{const post=await Post.findById(req.params.id).populate('author','isPrivate').populate('likes','name username avatarUrl isVerified').lean();if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(404);const fresh=await PostLike.find({post:post._id}).sort({createdAt:-1}).limit(300).populate('user','name username avatarUrl isVerified').lean();const map=new Map();for(const u of post.likes||[])if(u?._id)map.set(String(u._id),u);for(const x of fresh)if(x.user)map.set(String(x.user._id),x.user);res.json({ok:true,users:[...map.values()].map(u=>({id:u._id,name:u.name,username:u.username,avatarUrl:u.avatarUrl||'',isVerified:!!u.isVerified}))})});

router.post('/:id/save',requireAuth,async(req,res)=>{const post=await Post.findOne({_id:req.params.id,isHidden:false});if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);let row=await SavedPost.findOne({post:post._id,user:req.currentUser._id});const legacy=await User.exists({_id:req.currentUser._id,savedPosts:post._id});const saved=!!row||!!legacy;if(saved){if(row)await row.deleteOne();await User.updateOne({_id:req.currentUser._id},{$pull:{savedPosts:post._id}});post.saveCount=Math.max(0,(post.saveCount||0)-1);await recordEvent({user:req.currentUser._id,post:post._id,type:'unsave'})}else{await SavedPost.create({post:post._id,user:req.currentUser._id});post.saveCount=(post.saveCount||0)+1;await recordEvent({user:req.currentUser._id,post:post._id,type:'save'})}await post.save();recalcQuality(post._id).catch(()=>{});if(wantsJson(req))return res.json({ok:true,saved:!saved});res.redirect(req.get('referer')||'/feed')});

router.get('/:id/comments',async(req,res)=>{const post=await Post.findById(req.params.id).populate('author','isPrivate').populate('comments.user','username name avatarUrl isVerified').populate('comments.replyToUser','username name').lean();if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(404);const uid=String(req.currentUser?._id||'');const canModerate=!!req.currentUser&&(String(req.currentUser._id)===String(post.author?._id||post.author)||['admin','moderator'].includes(req.currentUser.role));const fresh=await Comment.find(canModerate?{post:post._id}:{post:post._id,isHidden:false}).sort({isPinned:-1,createdAt:1}).limit(500).populate('user','username name avatarUrl isVerified').populate('replyToUser','username name').lean();const likeIds=uid?await CommentLike.find({user:req.currentUser._id,comment:{$in:fresh.map(x=>x._id)}}).select('comment').lean():[];const likedSet=new Set(likeIds.map(x=>String(x.comment)));const legacy=(post.comments||[]).map(c=>({id:String(c._id),text:c.text,createdAt:c.createdAt,user:c.user?{id:String(c.user._id),username:c.user.username,name:c.user.name,avatarUrl:c.user.avatarUrl||'',isVerified:!!c.user.isVerified}:{id:'',username:'user',name:'User',avatarUrl:'',isVerified:false},replyToUser:c.replyToUser?{id:String(c.replyToUser._id),username:c.replyToUser.username,name:c.replyToUser.name}:null,likeCount:(c.likes||[]).length,liked:(c.likes||[]).some(id=>String(id)===uid),isPinned:false,isHidden:false,canDelete:canModerate||String(c.user?._id||c.user)===uid,canModerate,legacy:true}));const newer=fresh.map(c=>({id:String(c._id),text:c.text,createdAt:c.createdAt,user:c.user?{id:String(c.user._id),username:c.user.username,name:c.user.name,avatarUrl:c.user.avatarUrl||'',isVerified:!!c.user.isVerified}:{id:'',username:'user',name:'User',avatarUrl:'',isVerified:false},replyToUser:c.replyToUser?{id:String(c.replyToUser._id),username:c.replyToUser.username,name:c.replyToUser.name}:null,likeCount:c.likeCount||0,liked:likedSet.has(String(c._id)),isPinned:!!c.isPinned,isHidden:!!c.isHidden,canDelete:canModerate||String(c.user?._id||c.user)===uid,canModerate}));res.json({ok:true,postId:String(post._id),comments:[...legacy,...newer]})});

router.post('/:id/comment',requireAuth,async(req,res)=>{const text=String(req.body.text||'').trim().slice(0,400);if(!text)return wantsJson(req)?res.status(400).json({ok:false,error:'Izoh yozing.'}):res.redirect(req.get('referer')||'/feed');const post=await Post.findById(req.params.id);if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);let parent=null,replyToUser=null;if(req.body.replyToComment){const legacy=post.comments?.id?.(req.body.replyToComment);if(legacy)replyToUser=legacy.user;else{const target=await Comment.findOne({_id:req.body.replyToComment,post:post._id});if(target){parent=target._id;replyToUser=target.user}}}const owner=await User.findById(post.author).select('hiddenWords').lean();const restricted=await UserRelation.exists({owner:post.author,target:req.currentUser._id,type:'restrict'});const lower=text.toLowerCase();const wordHidden=(owner?.hiddenWords||[]).some(w=>w&&lower.includes(String(w).toLowerCase()));const spam=((text.match(/https?:\/\//gi)||[]).length>=3)||/(.)\1{12,}/.test(text);const autoHidden=!!(restricted||wordHidden||spam);const comment=await Comment.create({post:post._id,user:req.currentUser._id,text,parent,replyToUser,isHidden:autoHidden});post.commentCount=countLegacy(post).comments+1;await post.save();await recordEvent({user:req.currentUser._id,post:post._id,type:'comment'});recalcQuality(post._id).catch(()=>{});const targets=new Set();if(String(post.author)!==String(req.currentUser._id))targets.add(String(post.author));if(replyToUser&&String(replyToUser)!==String(req.currentUser._id))targets.add(String(replyToUser));if(!autoHidden)await Promise.all([...targets].map(user=>createNotification({user,actor:req.currentUser._id,type:'comment',post:post._id,text:replyToUser&&user===String(replyToUser)?'Izohingizga javob yozildi.':'Postingizga izoh yozildi.'})));if(wantsJson(req))return res.json({ok:true,commentId:String(comment._id),count:post.commentCount});res.redirect(req.get('referer')||'/feed')});

router.post('/:id/comments/:commentId/like',requireAuth,async(req,res)=>{const fresh=await Comment.findOne({_id:req.params.commentId,post:req.params.id});if(fresh){const row=await CommentLike.findOne({comment:fresh._id,user:req.currentUser._id});if(row){await row.deleteOne();fresh.likeCount=Math.max(0,(fresh.likeCount||0)-1)}else{await CommentLike.create({comment:fresh._id,user:req.currentUser._id});fresh.likeCount=(fresh.likeCount||0)+1;if(String(fresh.user)!==String(req.currentUser._id))await createNotification({user:fresh.user,actor:req.currentUser._id,type:'like',post:req.params.id,text:'Izohingizga yoqdi bosildi.'}).catch(()=>{})}await fresh.save();return res.json({ok:true,liked:!row,count:fresh.likeCount})}const post=await Post.findById(req.params.id);const c=post?.comments?.id?.(req.params.commentId);if(!c)return res.sendStatus(404);const uid=String(req.currentUser._id),liked=(c.likes||[]).some(x=>String(x)===uid);if(liked)c.likes.pull(req.currentUser._id);else c.likes.push(req.currentUser._id);await post.save();return res.json({ok:true,liked:!liked,count:c.likes.length})});

router.post('/:id/share-event',async(req,res)=>{const post=await Post.findOne({_id:req.params.id,isHidden:false}).populate('author','isPrivate');if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(404);await Post.updateOne({_id:post._id},{$inc:{shareCount:1}});if(req.currentUser)await recordEvent({user:req.currentUser._id,post:post._id,type:'share'});recalcQuality(post._id).catch(()=>{});res.json({ok:true})});
router.post('/:id/not-interested',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id).select('_id author');if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);await recordEvent({user:req.currentUser._id,post:post._id,type:'not_interested'});res.json({ok:true})});
router.post('/:id/hide-author',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id).select('_id author');if(!post)return res.sendStatus(404);if(String(post.author)===String(req.currentUser._id))return res.status(400).json({ok:false,error:'O‘zingizni yashirib bo‘lmaydi.'});if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);await recordEvent({user:req.currentUser._id,post:post._id,type:'hide_author'});res.json({ok:true})});
router.post('/:id/pin',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post||String(post.author)!==String(req.currentUser._id))return res.sendStatus(403);if(!post.isPinned)await Post.updateMany({author:req.currentUser._id,isPinned:true},{$set:{isPinned:false}});post.isPinned=!post.isPinned;await post.save();res.redirect('/u/'+req.currentUser.username)});
router.post('/:id/delete',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post)return res.sendStatus(404);if(String(post.author)!==String(req.currentUser._id)&&!['admin','moderator'].includes(req.currentUser.role))return res.sendStatus(403);const keys=[post.imageKey,...(post.media||[]).flatMap(m=>[m.key,m.thumbKey])];await deleteMany(keys);await Promise.all([PostLike.deleteMany({post:post._id}),SavedPost.deleteMany({post:post._id}),Comment.deleteMany({post:post._id}),Post.findByIdAndDelete(post._id),User.updateOne({_id:post.author},{$inc:{postCount:-1}})]);res.redirect('/feed')});
router.post('/:id/report',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id).select('author');if(!post)return res.sendStatus(404);if(!(await canAccessPost(req.currentUser,post)))return res.sendStatus(403);await Report.updateOne({reporter:req.currentUser._id,targetType:'post',targetId:post._id},{$setOnInsert:{reportedUser:post.author,reason:['spam','harassment','nudity','scam','impersonation','hate','other'].includes(req.body.reason)?req.body.reason:'other',details:String(req.body.details||'').slice(0,500)}},{upsert:true}).catch(()=>{});await Post.findByIdAndUpdate(post._id,{$inc:{reports:1}});res.redirect(req.get('referer')||'/feed')});
router.post('/:id/comments/:commentId/delete',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post)return res.sendStatus(404);const c=await Comment.findOne({_id:req.params.commentId,post:post._id});if(c){const allowed=String(c.user)===String(req.currentUser._id)||String(post.author)===String(req.currentUser._id)||['admin','moderator'].includes(req.currentUser.role);if(!allowed)return res.sendStatus(403);await Promise.all([CommentLike.deleteMany({comment:c._id}),Comment.deleteMany({parent:c._id}),c.deleteOne()]);post.commentCount=Math.max(0,(post.commentCount||1)-1);await post.save();return res.json({ok:true,count:post.commentCount})}const legacy=post.comments?.id?.(req.params.commentId);if(!legacy)return res.sendStatus(404);if(String(legacy.user)!==String(req.currentUser._id)&&String(post.author)!==String(req.currentUser._id)&&!['admin','moderator'].includes(req.currentUser.role))return res.sendStatus(403);legacy.deleteOne();post.commentCount=Math.max(0,(post.commentCount||post.comments.length+1)-1);await post.save();res.json({ok:true,count:post.commentCount})});
router.post('/:id/comments/:commentId/moderate',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post||String(post.author)!==String(req.currentUser._id)&&!['admin','moderator'].includes(req.currentUser.role))return res.sendStatus(403);const c=await Comment.findOne({_id:req.params.commentId,post:post._id});if(!c)return res.sendStatus(404);c.isHidden=req.body.action!=='show';await c.save();res.json({ok:true,isHidden:c.isHidden})});
router.post('/:id/comments/:commentId/report',requireAuth,async(req,res)=>{const c=await Comment.findOne({_id:req.params.commentId,post:req.params.id});if(!c)return res.sendStatus(404);try{await Report.create({reporter:req.currentUser._id,targetType:'comment',targetId:c._id,reportedUser:c.user,reason:['spam','harassment','nudity','scam','impersonation','hate','other'].includes(req.body.reason)?req.body.reason:'other',details:String(req.body.details||'').slice(0,500)})}catch(e){if(e.code!==11000)throw e}res.json({ok:true})});
router.post('/:id/comments/:commentId/pin',requireAuth,async(req,res)=>{const post=await Post.findById(req.params.id);if(!post||String(post.author)!==String(req.currentUser._id))return res.sendStatus(403);const c=await Comment.findOne({_id:req.params.commentId,post:post._id});if(!c)return res.sendStatus(404);c.isPinned=!c.isPinned;await c.save();res.json({ok:true,pinned:c.isPinned})});

router.post('/share-target',requireAuth,upload.array('images',10),async(req,res)=>{try{const files=req.files||[];if(!files.length)return res.redirect('/posts/create');const uploaded=[];for(const f of files)uploaded.push(await uploadFile(f,'posts',{maxEdge:1800,quality:84}));const caption=[req.body.title,req.body.text,req.body.url].filter(Boolean).join('\n').slice(0,2200);const media=uploaded.map(x=>({url:x.url,key:x.key,type:x.type==='video'?'video':'image',width:x.width||0,height:x.height||0,thumbUrl:x.thumbUrl||'',thumbKey:x.thumbKey||''}));const post=await Post.create({author:req.currentUser._id,caption,imageUrl:media[0].url,imageKey:media[0].key,media});await User.findByIdAndUpdate(req.currentUser._id,{$inc:{postCount:1}});res.redirect('/p/'+post._id)}catch(e){res.redirect('/posts/create')}});

module.exports=router;
