const router=require('express').Router();const multer=require('multer');const bcrypt=require('bcryptjs');
const User=require('../models/User');const Follow=require('../models/Follow');const UserRelation=require('../models/UserRelation');const LoginSession=require('../models/LoginSession');const {requireAuth}=require('../middleware/auth');const {uploadFile,deleteMany}=require('../services/r2');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(_,f,cb)=>cb(null,/^image\/(jpeg|png|webp|avif)$/.test(f.mimetype))});
async function settingsData(req,extra={}){const [blocked,muted,restricted,sessions,followers]=await Promise.all([UserRelation.find({owner:req.currentUser._id,type:'block'}).populate('target','name username avatarUrl').lean(),UserRelation.find({owner:req.currentUser._id,type:'mute'}).populate('target','name username avatarUrl').lean(),UserRelation.find({owner:req.currentUser._id,type:'restrict'}).populate('target','name username avatarUrl').lean(),LoginSession.find({user:req.currentUser._id,revokedAt:null}).sort({lastSeenAt:-1}).limit(20).lean(),Follow.find({following:req.currentUser._id,status:'accepted'}).populate('follower','name username avatarUrl').lean()]);return {title:'Sozlamalar',error:null,saved:false,blocked,muted,restricted,sessions,followers,...extra}}
router.get('/settings',requireAuth,async(req,res)=>res.render('profile/settings',await settingsData(req,{saved:req.query.saved==='1'})));
router.post('/settings',requireAuth,upload.single('avatar'),async(req,res)=>{try{const update={name:String(req.body.name||'').trim().slice(0,60),bio:String(req.body.bio||'').trim().slice(0,220),allowMessages:['everyone','following','nobody'].includes(req.body.allowMessages)?req.body.allowMessages:'following',allowMentions:['everyone','following','nobody'].includes(req.body.allowMentions)?req.body.allowMentions:'everyone',allowStoryReplies:req.body.allowStoryReplies==='on',showActivityStatus:req.body.showActivityStatus==='on',discoverableByPhone:req.body.discoverableByPhone==='on',notifyLikes:req.body.notifyLikes==='on',notifyComments:req.body.notifyComments==='on',notifyFollows:req.body.notifyFollows==='on',notifyMessages:req.body.notifyMessages==='on',notifyPush:req.body.notifyPush==='on',dataSaver:req.body.dataSaver==='on',isPrivate:req.body.isPrivate==='on',hiddenWords:String(req.body.hiddenWords||'').split(/[\n,]+/).map(x=>x.trim().toLowerCase()).filter(Boolean).slice(0,100)};if(!update.name)throw new Error('Ism bo‘sh bo‘lmasin.');if(req.file){const old=await User.findById(req.currentUser._id).select('avatarKey').lean();const x=await uploadFile(req.file,'avatars',{maxEdge:720,quality:84});update.avatarUrl=x.url;update.avatarKey=x.key;if(old?.avatarKey&&old.avatarKey!==x.key)deleteMany([old.avatarKey]).catch(()=>{})}await User.findByIdAndUpdate(req.currentUser._id,update);res.redirect('/settings?saved=1')}catch(e){res.status(400).render('profile/settings',await settingsData(req,{error:e.message||'Saqlanmadi.'}))}});
router.post('/settings/password',requireAuth,async(req,res)=>{const user=await User.findById(req.currentUser._id);if(!(await bcrypt.compare(String(req.body.currentPassword||''),user.passwordHash)))return res.status(400).render('profile/settings',await settingsData(req,{error:'Hozirgi parol noto‘g‘ri.'}));const np=String(req.body.newPassword||'');if(np.length<8)return res.status(400).render('profile/settings',await settingsData(req,{error:'Yangi parol kamida 8 belgi bo‘lsin.'}));user.passwordHash=await bcrypt.hash(np,12);user.sessionVersion=Number(user.sessionVersion||0)+1;await user.save();req.session.sessionVersion=user.sessionVersion;await LoginSession.updateMany({user:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});res.redirect('/settings?saved=1')});
router.post('/settings/sessions/revoke-all',requireAuth,async(req,res)=>{const user=await User.findById(req.currentUser._id);user.sessionVersion=Number(user.sessionVersion||0)+1;await user.save();req.session.sessionVersion=user.sessionVersion;await LoginSession.updateMany({user:req.currentUser._id,revokedAt:null},{$set:{revokedAt:new Date()}});res.redirect('/settings?saved=1')});
router.post('/settings/close-friends/:id',requireAuth,async(req,res)=>{const user=await User.findById(req.currentUser._id);const exists=user.closeFriends.some(x=>String(x)===String(req.params.id));if(exists)user.closeFriends.pull(req.params.id);else user.closeFriends.addToSet(req.params.id);await user.save();res.redirect('/settings#close-friends')});
module.exports=router;
