const router=require('express').Router();const crypto=require('crypto');
const Post=require('../models/Post');const User=require('../models/User');const Follow=require('../models/Follow');const PostView=require('../models/PostView');const {linkifyMentions}=require('../utils/mentions');const {getShareTargets}=require('../utils/socialUi');const {decoratePosts}=require('../utils/socialState');const {recordEvent}=require('../services/feed');
function baseUrl(req){return String(process.env.SITE_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'')}
function getCookie(req,name){const raw=req.headers.cookie||'';for(const part of raw.split(';')){const[k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return''}
function safeXml(v=''){return String(v).replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','\"':'&quot;'}[c]))}

async function canAccessPrivateAuthor(currentUser,author){
  if(!author?.isPrivate)return true;
  if(!currentUser)return false;
  if(String(currentUser._id)===String(author._id||author))return true;
  return !!(await Follow.exists({follower:currentUser._id,following:author._id||author,status:'accepted'}));
}
router.get('/p/:id',async(req,res)=>{let post=await Post.findOne({_id:req.params.id,isHidden:false}).populate('author','name username avatarUrl isVerified followerCount bio isPrivate').lean().catch(()=>null);if(!post||!post.author||!(await canAccessPrivateAuthor(req.currentUser,post.author)))return res.status(404).render('error',{title:'Post topilmadi',message:'Bu post mavjud emas yoki siz uchun yopiq.'});[post]=await decoratePosts([post],req.currentUser?._id);post.captionHtml=linkifyMentions(post.caption||'');const shareTargets=req.currentUser?await getShareTargets(req.currentUser._id,30):[];const description=(post.caption||`@${post.author.username} Lumi’da yangi vizual ulashdi.`).replace(/\s+/g,' ').trim().slice(0,180);const canonicalUrl=`${baseUrl(req)}/p/${post._id}`;const media=(post.media&&post.media[0])||{url:post.imageUrl,type:'image'};res.set('Cache-Control',req.currentUser?'private, no-store':'public, max-age=60, stale-while-revalidate=300');res.render('posts/show',{title:`${post.author.name} — Lumi post`,post,shareTargets,metaTitle:`${post.author.name} (@${post.author.username}) · Lumi`,metaDescription:description,metaImage:media.thumbUrl||media.url||post.imageUrl,canonicalUrl,metaType:'article',jsonLd:{'@context':'https://schema.org','@type':'SocialMediaPosting',headline:description.slice(0,110),image:[media.url||post.imageUrl],url:canonicalUrl,datePublished:post.createdAt,author:{'@type':'Person',name:post.author.name,url:`${baseUrl(req)}/u/${post.author.username}`}}})});
router.post('/api/posts/:id/view',async(req,res)=>{const post=await Post.findOne({_id:req.params.id,isHidden:false}).select('_id author tags viewCount').populate('author','isPrivate');if(!post||!post.author||!(await canAccessPrivateAuthor(req.currentUser,post.author)))return res.status(404).json({ok:false});let viewerKey,guestKey='';if(req.currentUser)viewerKey=`u:${req.currentUser._id}`;else{let vid=getCookie(req,'lumi_vid');if(!/^[a-f0-9]{32}$/i.test(vid)){vid=crypto.randomBytes(16).toString('hex');res.cookie('lumi_vid',vid,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*365})}const salt=process.env.VIEW_HASH_SALT||process.env.SESSION_SECRET||'lumi-view-salt';guestKey=crypto.createHash('sha256').update(vid+salt).digest('hex').slice(0,32);viewerKey=`g:${guestKey}`}let counted=false;try{await PostView.create({post:post._id,viewerKey,user:req.currentUser?._id||null});counted=true;await Post.updateOne({_id:post._id},{$inc:{viewCount:1}})}catch(e){if(e?.code!==11000)console.error('view tracking:',e.message)}await recordEvent({user:req.currentUser?._id||null,guestKey,post:post._id,type:'view'}).catch(()=>{});const fresh=await Post.findById(post._id).select('viewCount').lean();res.json({ok:true,counted,viewCount:fresh?.viewCount||0})});
router.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /chats\nDisallow: /settings\nDisallow: /admin\nDisallow: /notifications\nDisallow: /saved\nDisallow: /creator/analytics\nSitemap: ${baseUrl(req)}/sitemap.xml\n`));
router.get('/sitemap.xml',async(req,res)=>{const base=baseUrl(req);const users=await User.find({isSuspended:false,isPrivate:false}).sort({updatedAt:-1}).limit(5000).select('_id username updatedAt').lean();const publicIds=users.map(u=>u._id);const posts=publicIds.length?await Post.find({isHidden:false,author:{$in:publicIds}}).sort({updatedAt:-1}).limit(10000).select('_id updatedAt').lean():[];const urls=[{loc:`${base}/`,mod:new Date()},{loc:`${base}/feed`,mod:new Date()},{loc:`${base}/explore`,mod:new Date()},...users.map(u=>({loc:`${base}/u/${encodeURIComponent(u.username)}`,mod:u.updatedAt})),...posts.map(p=>({loc:`${base}/p/${p._id}`,mod:p.updatedAt}))];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`\n<url><loc>${safeXml(x.loc)}</loc><lastmod>${new Date(x.mod).toISOString()}</lastmod></url>`).join('')}\n</urlset>`) });
module.exports=router;
