const router=require('express').Router();const crypto=require('crypto');
const User=require('../models/User');const Post=require('../models/Post');const PostView=require('../models/PostView');const Report=require('../models/Report');const Story=require('../models/Story');const Notification=require('../models/Notification');const SavedPost=require('../models/SavedPost');const Follow=require('../models/Follow');const UserRelation=require('../models/UserRelation');const FeedEvent=require('../models/FeedEvent');
const {requireAuth}=require('../middleware/auth');const {getStoryPeople,getGuestStoryPeople,getShareTargets}=require('../utils/socialUi');const {linkifyMentions}=require('../utils/mentions');const {createNotification}=require('../services/notify');const {normalizePhone,isValidPhone}=require('../utils/phone');const {buildFeed,recordEvent}=require('../services/feed');const {decoratePosts,filterVisiblePosts,isFollowing,followCounts}=require('../utils/socialState');
const {getAdConfig,getAdsForPlacement}=require('../services/ads');
function getCookie(req,name){const raw=req.headers.cookie||'';for(const part of raw.split(';')){const[k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return''}
function guestKey(req){const vid=getCookie(req,'lumi_vid');if(!vid)return'';return crypto.createHash('sha256').update(vid+(process.env.VIEW_HASH_SALT||process.env.SESSION_SECRET||'lumi-view-salt')).digest('hex').slice(0,32)}


router.get('/feed',async(req,res)=>{const mode=['foryou','following','new'].includes(req.query.tab)?req.query.tab:'foryou';const me=req.currentUser?await User.findById(req.currentUser._id).lean():null;let posts=await buildFeed(me,{mode,limit:50,nonce:req.query.refresh||Date.now()});posts=await decoratePosts(posts,me?._id);const [storyPeople,shareTargets,adConfig,feedAds]=await Promise.all([me?getStoryPeople(me._id,18):getGuestStoryPeople(18),me?getShareTargets(me._id,30):Promise.resolve([]),getAdConfig(),getAdsForPlacement('feed',me,12)]);res.set('Cache-Control','no-store');res.render('feed',{title:'Lumi feed',posts,storyPeople,shareTargets,adConfig,feedAds,feedNonce:Date.now(),feedMode:mode,metaDescription:'Lumi feed — For You algoritmi, following va yangi postlar.'})});

router.post('/api/feed/event',async(req,res)=>{const allowed=['impression','view','dwell','open_comments','profile_visit','not_interested','share'];const type=allowed.includes(req.body.type)?req.body.type:null;if(!type||!req.body.post)return res.status(400).json({ok:false});const gk=guestKey(req);await recordEvent({user:req.currentUser?._id||null,guestKey:gk,post:req.body.post,type,value:Math.min(120,Math.max(0,Number(req.body.value)||1))});res.json({ok:true})});

router.get('/explore',async(req,res)=>{const q=String(req.query.q||'').trim();const term=q.replace(/^[@#]+/,'').trim();const phone=normalizePhone(q);let users=[],posts=[];if(q){try{users=await User.find({$text:{$search:term||q},isSuspended:false}).sort({score:{$meta:'textScore'},followerCount:-1}).limit(24).lean()}catch(_){const rx=new RegExp((term||q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');users=await User.find({isSuspended:false,$or:[{username:rx},{name:rx}]}).limit(24).lean()}if(req.currentUser&&isValidPhone(phone)){const byPhone=await User.findOne({phone,discoverableByPhone:true,isSuspended:false}).lean();if(byPhone&&!users.some(x=>String(x._id)===String(byPhone._id)))users.unshift(byPhone)}try{posts=await Post.find({$text:{$search:term||q},isHidden:false}).sort({score:{$meta:'textScore'},qualityScore:-1}).limit(42).populate('author','name username avatarUrl isVerified isPrivate').lean()}catch(_){const rx=new RegExp((term||q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');posts=await Post.find({isHidden:false,$or:[{caption:rx},{tags:(term||q).toLowerCase()}]}).sort({qualityScore:-1,viewCount:-1}).limit(42).populate('author','name username avatarUrl isVerified isPrivate').lean()}}else{posts=await Post.find({isHidden:false}).sort({qualityScore:-1,viewCount:-1,createdAt:-1}).limit(42).populate('author','name username avatarUrl isVerified isPrivate').lean();users=await User.find({isSuspended:false}).sort({followerCount:-1,createdAt:-1}).limit(24).lean()}posts=await filterVisiblePosts(posts,req.currentUser?._id);posts=await decoratePosts(posts,req.currentUser?._id);const [adConfig,exploreAds]=await Promise.all([getAdConfig(),getAdsForPlacement('explore',req.currentUser,2)]);res.render('explore',{title:q?`${q} — qidiruv`:'Kashf etish',users,posts,q,adConfig,exploreAds,metaDescription:q?`Lumi’da “${q}” bo‘yicha qidiruv.`:'Lumi’da trend postlar va creatorlarni kashf eting.'})});

router.get('/u/:username',async(req,res)=>{const profile=await User.findOne({username:req.params.username.toLowerCase(),isSuspended:false}).lean();if(!profile)return res.status(404).render('error',{title:'Topilmadi',message:'Profil topilmadi.'});const blocked=req.currentUser?await UserRelation.exists({type:'block',$or:[{owner:profile._id,target:req.currentUser._id},{owner:req.currentUser._id,target:profile._id}]}):false;if(blocked)return res.status(404).render('error',{title:'Topilmadi',message:'Profil topilmadi.'});const follow=req.currentUser?await Follow.findOne({follower:req.currentUser._id,following:profile._id}).lean():null;const canSee=!profile.isPrivate||String(req.currentUser?._id||'')===String(profile._id)||follow?.status==='accepted';let posts=canSee?await Post.find({author:profile._id,isHidden:false}).sort({isPinned:-1,createdAt:-1}).lean():[];posts=await decoratePosts(posts,req.currentUser?._id);const [storyCount,counts,highlights,adConfig,profileAds]=await Promise.all([canSee?Story.countDocuments({author:profile._id,expiresAt:{$gt:new Date()}}):0,followCounts(profile._id,profile),canSee?Story.find({author:profile._id,isHighlight:true}).sort({createdAt:-1}).limit(12).lean():[],getAdConfig(),getAdsForPlacement('profile',req.currentUser,2)]);if(req.currentUser&&String(req.currentUser._id)!==String(profile._id))recordEvent({user:req.currentUser._id,post:posts[0]?._id,type:'profile_visit'}).catch(()=>{});res.render('profile/show',{title:'@'+profile.username,profile:{...profile,...counts},posts,storyCount,highlights,isFollowing:follow?.status==='accepted',followPending:follow?.status==='pending',canSee,adConfig,profileAds,metaTitle:`${profile.name} (@${profile.username}) · Lumi`,metaDescription:(profile.bio||`${profile.name} ning Lumi profili.`).slice(0,180),metaImage:profile.avatarUrl||(posts[0]?.imageUrl||''),metaType:'profile'})});

router.get('/saved',requireAuth,async(req,res)=>{const rows=await SavedPost.find({user:req.currentUser._id}).sort({createdAt:-1}).limit(500).populate({path:'post',match:{isHidden:false},populate:{path:'author',select:'name username avatarUrl isVerified'}}).lean();let posts=rows.map(x=>x.post).filter(Boolean);const me=await User.findById(req.currentUser._id).populate({path:'savedPosts',match:{isHidden:false},populate:{path:'author',select:'name username avatarUrl isVerified'}}).lean();const map=new Map(posts.map(p=>[String(p._id),p]));for(const p of me?.savedPosts||[])map.set(String(p._id),p);posts=await decoratePosts([...map.values()],req.currentUser._id);posts=posts.map(p=>({...p,captionHtml:linkifyMentions(p.caption||'')}));res.render('saved',{title:'Saqlanganlar',posts})});

router.post('/u/:username/follow',requireAuth,async(req,res)=>{const target=await User.findOne({username:req.params.username.toLowerCase(),isSuspended:false});if(!target||String(target._id)===String(req.currentUser._id))return res.redirect('/feed');const blocked=await UserRelation.exists({$or:[{owner:req.currentUser._id,target:target._id,type:'block'},{owner:target._id,target:req.currentUser._id,type:'block'}]});if(blocked)return res.redirect('/u/'+target.username);let row=await Follow.findOne({follower:req.currentUser._id,following:target._id});if(row){const accepted=row.status==='accepted';await row.deleteOne();if(accepted){await Promise.all([User.findByIdAndUpdate(req.currentUser._id,{$inc:{followingCount:-1}}),User.findByIdAndUpdate(target._id,{$inc:{followerCount:-1}})])}}else{const status=target.isPrivate?'pending':'accepted';row=await Follow.create({follower:req.currentUser._id,following:target._id,status});if(status==='accepted')await Promise.all([User.findByIdAndUpdate(req.currentUser._id,{$inc:{followingCount:1}}),User.findByIdAndUpdate(target._id,{$inc:{followerCount:1}})]);await createNotification({user:target._id,actor:req.currentUser._id,type:status==='pending'?'follow_request':'follow',text:status==='pending'?`@${req.currentUser.username} obuna so‘rovi yubordi.`:`@${req.currentUser.username} sizga obuna bo‘ldi.`}).catch(()=>{})}res.redirect('/u/'+target.username)});

router.post('/follow-requests/:id/:action',requireAuth,async(req,res)=>{const row=await Follow.findOne({_id:req.params.id,following:req.currentUser._id,status:'pending'});if(!row)return res.sendStatus(404);if(req.params.action==='accept'){row.status='accepted';await row.save();await Promise.all([User.findByIdAndUpdate(row.follower,{$inc:{followingCount:1}}),User.findByIdAndUpdate(row.following,{$inc:{followerCount:1}})]);await createNotification({user:row.follower,actor:req.currentUser._id,type:'follow',text:'Obuna so‘rovingiz qabul qilindi.'})}else await row.deleteOne();res.redirect('/notifications')});

router.post('/u/:username/relation',requireAuth,async(req,res)=>{const target=await User.findOne({username:req.params.username.toLowerCase()});const type=['block','mute','restrict'].includes(req.body.type)?req.body.type:null;if(!target||!type||String(target._id)===String(req.currentUser._id))return res.sendStatus(400);const existing=await UserRelation.findOne({owner:req.currentUser._id,target:target._id,type});if(existing)await existing.deleteOne();else await UserRelation.create({owner:req.currentUser._id,target:target._id,type});if(type==='block'&&!existing){const rows=await Follow.find({$or:[{follower:req.currentUser._id,following:target._id},{follower:target._id,following:req.currentUser._id}],status:'accepted'}).lean();await Follow.deleteMany({$or:[{follower:req.currentUser._id,following:target._id},{follower:target._id,following:req.currentUser._id}]});for(const r of rows){await Promise.all([User.updateOne({_id:r.follower},{$inc:{followingCount:-1}}),User.updateOne({_id:r.following},{$inc:{followerCount:-1}})])}}res.json({ok:true,enabled:!existing})});

router.post('/u/:username/report',requireAuth,async(req,res)=>{const target=await User.findOne({username:req.params.username.toLowerCase()}).select('_id');if(!target||String(target._id)===String(req.currentUser._id))return res.sendStatus(400);try{await Report.create({reporter:req.currentUser._id,targetType:'user',targetId:target._id,reportedUser:target._id,reason:['spam','harassment','nudity','scam','impersonation','hate','other'].includes(req.body.reason)?req.body.reason:'other',details:String(req.body.details||'').slice(0,500)})}catch(e){if(e.code!==11000)throw e}res.json({ok:true})});

router.get('/notifications',requireAuth,async(req,res)=>{const items=await Notification.find({user:req.currentUser._id}).sort({lastActivityAt:-1,createdAt:-1}).limit(100).populate('actor','name username avatarUrl isVerified').populate('actors','name username avatarUrl').populate('post','imageUrl media').populate('story','mediaUrl').lean();const requests=await Follow.find({following:req.currentUser._id,status:'pending'}).sort({createdAt:-1}).limit(30).populate('follower','name username avatarUrl isVerified').lean();await Notification.updateMany({user:req.currentUser._id,read:false},{$set:{read:true}});res.render('notifications',{title:'Bildirishnomalar',items,requests})});

router.get('/creator/analytics',requireAuth,async(req,res)=>{const since30=new Date(Date.now()-30*864e5),since7=new Date(Date.now()-7*864e5);const posts=await Post.find({author:req.currentUser._id}).sort({createdAt:-1}).lean();const ids=posts.map(p=>p._id);const [events30,events7,uniqueRows,followerGrowth,bestHours]=await Promise.all([FeedEvent.aggregate([{$match:{author:req.currentUser._id,createdAt:{$gte:since30}}},{$group:{_id:'$type',count:{$sum:1},value:{$sum:'$value'}}}]),FeedEvent.aggregate([{$match:{author:req.currentUser._id,createdAt:{$gte:since7}}},{$group:{_id:'$type',count:{$sum:1},value:{$sum:'$value'}}}]),ids.length?PostView.aggregate([{$match:{post:{$in:ids},viewedAt:{$gte:since30}}},{$group:{_id:'$viewerKey'}},{$count:'n'}]):Promise.resolve([]),Follow.aggregate([{$match:{following:req.currentUser._id,status:'accepted',createdAt:{$gte:since30}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt',timezone:'+05:00'}},count:{$sum:1}}},{$sort:{_id:1}}]),FeedEvent.aggregate([{$match:{author:req.currentUser._id,type:{$in:['view','dwell','like','comment','save','share']},createdAt:{$gte:since30}}},{$group:{_id:{$hour:{date:'$createdAt',timezone:'+05:00'}},score:{$sum:{$cond:[{$eq:['$type','share']},8,{$cond:[{$eq:['$type','save']},6,{$cond:[{$eq:['$type','comment']},5,1]}]}]}},events:{$sum:1}}},{$sort:{score:-1}},{$limit:6}])]);const totals=posts.reduce((a,p)=>(a.views+=p.viewCount||0,a.likes+=Math.max(Number(p.likeCount||0),p.likes?.length||0),a.comments+=Math.max(Number(p.commentCount||0),p.comments?.length||0),a.saves+=p.saveCount||0,a.shares+=p.shareCount||0,a),{views:0,likes:0,comments:0,saves:0,shares:0});const top=[...posts].sort((a,b)=>(b.qualityScore||0)-(a.qualityScore||0)).slice(0,8);const engagement=totals.views?((totals.likes+totals.comments+totals.saves+totals.shares)/totals.views*100):0;res.render('creator/analytics',{title:'Creator Analytics',totals,events30,events7,top,uniqueReach30:uniqueRows[0]?.n||0,followerGrowth,bestHours,engagement})});
module.exports=router;
