plugins {
    id 'com.android.application'
}

android {
    namespace 'uz.hallaym.lumi'
    compileSdk 36

    defaultConfig {
        applicationId 'uz.hallaym.lumi'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '1.0.2'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
